### ISSUE TITLE
using import instead of require

### ISSUE THREAD

**Issue by msimonc** [browniefed/htmlparser2-react#1]
When I do:

import reactParser from 'react-htmlparser2';

or
import { reactParser } from 'react-htmlparser2';

I get:

./~/react-htmlparser2/~/htmlparser2/~/entities/maps/entities.json
Module parse failed: ... /node_modules/entities/maps/entities.json Line 1: Unexpected token :
You may need an appropriate loader to handle this file type.

Thanks

**Comment by browniefed** [comment]
Hello, I no longer maintain this and it's HIGHLY recommended to use other modules that may accomplish similar things.
This was last tested on v.12 or .13 of React, so it's be quite some time.
